name: Verify Secrets

on:
  workflow_dispatch: # run manually
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load and verify secrets
        env:
          OAUTH__GOOGLE__ID: ${{ secrets.OAUTH_GOOGLE_ID }}
          OAUTH__GOOGLE__SECRET: ${{ secrets.OAUTH_GOOGLE_SECRET }}
          OPENAI__API__KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI__ENDPOINT: ${{ secrets.OPENAI_ENDPOINT }}
          EMAIL__CONFIRMATION__PASSWORD:  ${{ secrets.EMAIL_CONFIRMATION_PASSWORD }}
        run: |
          echo "Secrets have been loaded into environment variables."

          # Check each one without exposing values
          for name in OAUTH_GOOGLE_ID OAUTH_GOOGLE_SECRET OPENAI_API_KEY OPENAI_ENDPOINT; do
            if [ -z "${!name}" ]; then
              echo "$name is missing!"
              exit 1
            else
              echo "$name is set."
            fi
          done

          echo "All secrets are available. You can use them in your .NET app like normal."
